<form method="POST" action="/registration.php">
    <div>
        <label for="name">Имя</label>
        <input id="name" type="text" name="name" />
    </div>
    <div>
        <label for="email">E-mail</label>
        <input id="email" type="text" name="email" />
    </div>
    <div>
        <label for="password">Пароль</label>
        <input id="password" type="password" name="password" />
    </div>
    <div>
        <input id="submit" type="submit" value="Зарегистрироваться" />
    </div>
</form>
